config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'signup' => 'user#new'
  post '/users' => 'user#create'
  get '/posts/index' => 'posts#index'

  resources :users
  resources :posts do
    resources :comments
  end 


  root 'user#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :post 
end

app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  validates_presence_of :description
  has_many :comments

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :posts
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comment.create(params[:comment].permit(:content))
    redirect_to post_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.create(post_params)
    redirect_to posts_url
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:description, :photo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(login_params[:email])
    if @user && @user.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to '/posts/index'
    else
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def login_params
    params.require(:login).permit(:email, :password)
  end


end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  def new; end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to '/posts/index'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<header>
  <div>
    <h3>
      <p>Already created an account?</p>

      Login

    </h3>
  </div>
</header>

<center><br>
  <h1>
    <s></s>GinsterGram</h1>
</center><br>

<%= form_for(@user) do |form| %>
<div>
  <h3>&nbsp;&nbsp;&nbsp;&nbsp; Create an Account &nbsp;</h3><br>
  <%= form.text_field :name, class: 'textbox-style', :required => true, :placeholder => 'Type your username' %>
  <br><br>
  <%= form.text_field :email, class: 'textbox-style', :required => true, :placeholder => 'Type your email' %>
  <br><br>
  <%= form.password_field :password, class: 'textbox-style', :required => true, :placeholder => 'Type your password' %>
  <br><br>
  <%= form.submit "Submit", class: 'button' %><br>&nbsp;</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<head>
  <%= link_to logout_path do %>
  logout
<% end %>
<center>
  <%= link_to new_post_path do %><br>

  <h2><%= image_tag("mchammer.gif") %>New post<%= image_tag("mchammer.gif") %></h2>

  <br>
  <br>
</head>
<%= image_tag("divider.gif") %>
</center>

<body>

<% end %>

<% @posts.each do |post| %>
<div>
  <center>
    <img class="img" src="<%= post.photo %>" width="350" height="350">
    <p><%= post.description %></p>

    <%= image_tag("divider.gif") %>
    <br>
  </center>
</div>
</body>
<% end %>
<center>
<%= image_tag("audience.gif") %>
</center>

app/views/posts/new.html.erb
<div>
  <center>
    <%= image_tag("mchammer.gif") %><br>
    <%= image_tag("rainbow.gif") %>
    <h1><%= image_tag("new.gif") %>New Post</h1>
    <center>
      <div style="style" media="screen">

        <%= form_for @post do |form| %>

        <%= form.text_field :description, :required => true, :placeholder => 'description' %>
        <br><br>

        <div style="padding-left: 130px">
          <%= form.file_field :photo, :required => true, :placeholder => 'image' %>
        </div>
        <br><br>
        <%= form.submit "Submit" %><br></div>

    <% end %>
    <%= image_tag("rainbow.gif") %><br>
    <%= image_tag("mchammer.gif") %>
  </center>

app/views/user/new.html.erb
<header>
  <center>
    <div>
      <h3>
        <%= image_tag("ie_logo.gif") %>
        <%= image_tag("noframes.gif") %>
        <%= image_tag("notepad.gif") %>
        <%= image_tag("wabwalk.gif", size: "75x75") %>
        <p>Already created an account?</p>
        <%= link_to '/login' do %>
        Login
      <% end %>

    </h3>
  </div>
</center>
</header>

<center><br>
<h1>
  <s></s><br><%= image_tag("7upspot.gif") %>GinsterGram<%= image_tag("7upspot.gif") %></h1>
<%= image_tag("rainbow.gif") %><br>
<%= image_tag("ginster2.jpg", size: "300x200") %><br>
<%= image_tag("rainbow.gif") %><br>
</center><br>

<%= form_with scope: :user, url: users_path do |form| %>

<center>
<div>
  <h3>Create an Account</h3><br>
  <%= form.text_field :name, class: 'textbox-style', :required => true, :placeholder => 'Type your username' %>
  <br><br>
  <%= form.text_field :email, class: 'textbox-style', :required => true, :placeholder => 'Type your email' %>
  <br><br>
  <%= form.password_field :password, class: 'textbox-style', :required => true, :placeholder => 'Type your password' %>
  <br><br>
  <%= form.submit "Submit", class: 'button' %><br><%= image_tag("flames.gif", size: "300x200") %><br><%= image_tag("counter2.gif") %></center>

</div>

<% end %>